/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as IndexRouteImport } from './routes/index'

const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artist'
  id: '__root__' | '/' | '/artist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistRoute: typeof ArtistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
